name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Install deps
      - name: Install backend deps
        working-directory: backend
        run: npm ci

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      # Start backend on :5000 (no backgrounding)
      - name: Start backend
        working-directory: backend
        run: |
          npm start &
          # Wait for backend to be ready
          sleep 10  # Adjust this if needed, depending on how long your backend takes to start

      # Start frontend on :3000 (no backgrounding)
      - name: Start frontend
        working-directory: frontend
        env:
          BROWSER: none
          PORT: 3000
        run: |
          npm start &
          # Wait for frontend to be ready
          sleep 15  # Adjust this as well, depending on frontend startup time

      # Run Newman API tests
      - name: Run Newman (API)
        working-directory: backend
        run: npx newman run tests/postman/todo-api.postman_collection.json -r cli

      # Playwright UI tests
      - name: Install Playwright browsers
        working-directory: frontend
        run: npx playwright install --with-deps

      - name: Run Playwright (UI)
        working-directory: frontend
        run: npx playwright test ./tests/E2E.spec.js
